### ISSUE TITLE
Can't change any profile info

### ISSUE THREAD

**Issue by matuskropuch** [jerguslejko/interns#1]
After submitting the form to update profile info I get the "Whoops, looks like something went wrong." error page.

**Comment by jerguslejko** [comment]
I have troubles reproducing the error. which fields are you trying to update?

**Comment by matuskropuch** [comment]
Name and password fields

**Comment by jerguslejko** [comment]
weird. does not seem to cause the error on my machine...

also, I cannot take you seriously as you *do not* have a profile picture...

**Comment by jerguslejko** [comment]
AHA!

as I found out, my sqlite installation does not work in _strict_mode_...

fixed! (#15) thank you
